pipeline {
  agent {
    node {
      label 'maven'
    }
  }


  options {
    timeout(time: "20", unit: 'MINUTES')
  }

  stages {
    stage ('load-test'){
      steps {
          sh 'sleep 20; echo "test complete"'
      }
    }

  }
}
